apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260612-190238-wh6r2d7d9gmd-service
spec:
  selector:
    app: enterprise-system-20260612-190238-wh6r2d7d9gmd
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
